### Health Check
GET http://localhost:3000/api/health

### Register user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "PronostiqueurFou",
  "email": "testdelemail@gmail.com",
  "password": "1MotdepasseINCROYABLE!!!"
}

### Login user
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "testdelemail@gmail.com",
  "password": "1MotdepasseINCROYABLE!!!"
}

### auth/me
GET http://localhost:3000/api/auth/me
Cookies: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1YTBlMDMyNi1iMmRiLTQ0YWEtYjY1NC03OTA5NmFhYTQ2MjAiLCJ1c2VyUm9sZSI6Ik1FTUJFUiIsImlhdCI6MTc2ODQ4NTU3MiwiZXhwIjoxNzY4NDg5MTcyfQ.Wg10Gn5LqAR3ePcdd8vUqZgGXLFU8hNn_X85wIkpuiE


### Get All Users
GET http://localhost:3000/api/users

### Get One User
GET http://localhost:3000/api/users/user_1

### Get All Matches
GET http://localhost:3000/api/matches

### Get Match by ID
GET http://localhost:3000/api/matches/2007

### Get All Predictions
GET http://localhost:3000/api/predictions

### Get One Predictions
GET http://localhost:3000/api/predictions/88dde2de-1be4-4cbc-8b1b-4e760728708f

### Create one Prediction
POST http://localhost:3000/api/predictions
Content-Type: application/json

{
  "user_id": "24eeeca0-344f-4634-a60b-90b7fdab5c6f",
  "match_id": "69d27a15-4fb8-45f2-8018-8ed2bb55359a",
  "prediction_value": "HOME"
}
